# Profile section
profile:
  first_name: Kevin
  last_name: Gamuzza
  #picture: https://cdn.glitch.com/88028f3b-2a37-4207-9b84-e56ad97a9d3d%2Frodo_2021.png?v=1622471953248   # Hosted picture
  picture: static/img/kevin_gamuzza.jpg  # Local picture
  contact:
    address_one: Sonnrueti 5, 6233 Bueron
    address_two:
    phone: +41 76 ASK-4-IT!
  email: k.gamuzza@hotmail.com
  description: |
    I call myself an Agile Project Manager and Scrum Master with a pragmatic approach of using agile Frameworks as well as a keen interest in technology itself.

    I have a strong focus on minimal overhead or micromanagement and appreciate working together with experts in order to create great products and services that make a difference in the marketplace.

    I have a strong background in Business Administration and Strategy but I speak and understand the language of the world of technology as well. I

    have an affinity for technology and its development and see myself as a life long learner in this area. Most of my technological know how is selftought and

    I don't see a reason in changing that habit any time soon since the journey is truly rewarding.


# Social section
social:
  #website:
  github: https://github.com/kevgam
  twitter: https://twitter.com/BlkSec24
  linkedin: https://www.linkedin.com/in/kevin-gamuzza-11b43258/
  #facebook:
  #dev: https://dev.to/rodolfoferro
  #medium: https://medium.com/@FerroRodolfo


# Experience section
experience:
  item8:
    position: Product Owner
    company: Axon Vibe AG
    from: February 2022
    to: Present
    description: >
      Acted as a liaison between the development team and stakeholders to ensure product requirements are understood and met / 
      Collaborated with stakeholders to define product requirements and prioritize features / 
      Managed a product roadmap that identified customer needs and aligned with the company’s overall business strategy / 
      Established and maintained relationships with customers to understand their needs and ensure successful product delivery / 
      Developed and maintained a product backlog that tracked customer needs, features, and user stories / 
      Used customer feedback to drive product decisions and ensure customer satisfaction
    link:
  item7:
    position: Scrum Master SAFe
    company: SBB AG
    from: February 2021
    to: January 2022
    description: >
      Servant Leader in the Application Integration Service (API Management / Kafka / Job-Scheduling)
      with responsibilities in Impediment Management / as Change Agent / Team-Performance Development and Continuous Improvement
    link:
  item6:
    position: Professional IT-Project Manager
    company: SBB AG
    from: Mai 2019
    to: January 2021
    description: >
      Project Lead and Scrum Master in Projects such as Development of a central API-Management Plattform, Migration Projects
      with Splunk, Lifecycle Projects with 3Scale API Management and Redhat Single Sign-On Auth-Server, Product Owner of Single Sign-On Auth-Server and establishment of a
      24/7 Operations DevOps Team
    link: https://developer.sbb.ch/home
  item5:
    position: Junior IT-Project Manager
    company: SBB AG
    from: September 2017
    to: Mai 2019
    description: >
      Project Lead in evaluation and development of container Web-Application Firewall based on ModSecurity.
      Project Lead in development of REST API Service to access employeedata in a secure way and self-service model
    link:
  item4:
    position: User Service Manager
    company: SBB AG
    from: Dezember 2015
    to: September 2017
    description: >
      Working as a User Service Manager 1st-Level Support responsible for Incident-, Problem- and Configuration Management. Part Time Role in
      Workforce Management and Callvolume Forecasting.
    link:
  item3:
    position: User Service Manager
    company: Freestar Informatik AG
    from: July 2015
    to: December 2015
    description: >
      Working as a User Service Manager 1st-Level Support responsible for Incident-, Problem- and Configuration Management as
      external employee for the Service Desk of SBB AG.
    link:
  item2:
    position: Sales Consultant
    company: Swisscom AG
    from: February 2014
    to: July 2015
    description: >
      Consulting Customers, Sales and Order Management.
  item1:
    position: Sales Consultant
    company: Sunrise Telecommunications AG
    from: November 2011
    to: January 2014
    description: >
      Consulting Customers, Sales and Order Management.
  reference:


# Education section
education:
  item1:
    institution: ZHAW School of Engineering
    program: MAS in Computer Science
    description:
      Graduates of the MAS Computer Science are able to systematically analyze problems in computer science and develop and implement scalable solutions. This enables them to play a key role in shaping the digital transformation and to contribute to the success of their company.
      The MAS Degree consists of 4 seperate CAS and masters thesis. My choice of CAS within the degree consists of Computer Science Fundamentals 1+2 / Object Oriented Programming / Information Engineering.
    from: March 2021
    to: July 2023
  item2:
    institution: University of Applied Sciences of North Western Switzerland (FHNW)
    program: Msc Business Information Systems
    description: Enabling students to use information and information technology for the success of a company in the globalized, networked and digitized economy. By looking beyond the current state of practice, students learn result-oriented problem-solving strategies and can thus drive innovations in a company.
    from: September 2017
    to: July 2018
  item3:
    institution: Berne University of Applied Sciences (BFH)
    program: BSc in Business Administration with specialisation in Strategy and Digital Marketing
    description: The degree in business administration deals with internal and external processes as well as various tasks and functions in the company (marketing, finance and accounting, controlling, human resources, production, logistics, strategy and planning, etc.). Future-oriented questions about the direction of the company as well as the right design of the environment and optimal interaction with the environment are the focus.
      The subject, method, social and personal skills are ideally combined in the course content. The result is a degree program that is optimally geared towards the requirements of a future specialist and management career.
    from: June 2017
    to: August 2017
  reference:


# Community section:
community:
  item0:
    institution: Omdena
    program: Community Builder
    description: "Selected as a community builder at Omdena due to exemplary performance in their AI challenge on the tree identification challenge to prevent fire outbursts."
    from: September 2019
    to: Present
    link: https://omdena.com
  item1:
    institution: Future Lab
    program: Co-founder and Coordinator
    description: "Co-founder and coordinator of Future Lab, a community of tech developers for the future. We maily work under three axis: a) Develop awesome tech based projects, b) Share knowledge with the community, and c) Networking with other communities. As a member of Future Lab I have participated on big events such as Talent Land with an AI talk."
    from: April 2017
    to: Present
    link: https://futurelab.mx
  item2:
    institution: GitHub Education
    program: GitHub Campus Experts Program
    description: Mexican member of the GitHub Campus Experts Program, encouraging to empower other student communities. I also serve as a mentor in different events such as Startup Weekends, hackathons, innovation events, etc.
    from: October 2017
    to: Present
    link: https://githubcampus.expert/RodolfoFerro/
  item3:
    institution: Clubes de Ciencia México
    program: Guanajuato Comitee Member and Instructor
    description: Co-organizer of the intensive one-week summer science workshops of Clubes de Ciencia México in Guanajuato. Besides organizing, I have participated teaching science workshops (in particular a physics workshop, based on a Nobel Prize design, and artificial intelligence workshops) for high school and undergrad students.
    from: January 2015
    to: Present
    link: https://www.clubesdeciencia.mx
  item4:
    institution: Google Programs
    program: Google Student Ambassador and GDG
    description: Served as a Google Student Ambassador Latam for the University of Guanajuato, empowering the student community with Googleness and Google technologies to make their life easier. Currently helping the GDG León with tech talks and workshops about AI as a core member of the team. Do cool things that matter.
    from: August 2014
    to: July 2015
    link: https://www.meetup.com/es/GDGLeon/
  reference: https://rodolfoferro.xyz/resume/



# Skills section
tools:
  # Consider that the following are fa icons:
  #   https://fontawesome.com/icons?d=gallery&s=brands
  - python
  - jira
  - confluence
  - bitbucket
  - atlassian
  - git-alt
  - github
  - docker
  - aws
  - linux
  - jenkins
  - raspberry-pi
  - slack

extra_skills:
  # - Facebook Messenger, Telegram, and SMS bots
  - Professional - Agile Project Management and Product Development (Scrum, Kanban)
  - Professional - Scrum Master Role
  - Professional - Product Owner Role
  - Professional - Atlassian Toolsuite (Jira, Confluence)
  - Professional - Stakeholder Management
  - Professional - Financial Project Controlling as well as Risk Management
  - Junior - Programming Languages (Python, Javascript, Java)
  - Junior - Webdevelopment Frameworks (Flask, Bootstrap)
  - Junior - Hardware/Embedded Systems Programming on Arduino and Raspberry Pi Plattform (Python, C/C++, Node-Red)
  - Junior - SQL/Database Programming (MariaDB)
  - Junior - Git/Bitbucket


# Talks and workshops section
workshops:
  item0:
    event: TEDxUNAMLeón
    workshop: AI in modern times, February 2020.
    material:
    link: https://www.ted.com/tedx/events/35293
  item1:
    event: PyCon Colombia 2020
    workshop: 'Workshop – DLaaS: Building cloud-based intelligent solutions, February 2020.'
    material: https://github.com/RodolfoFerro/PyConCo20
    link: https://www.pycon.co/ponentes/rodolfo-ferro/
  item2:
    event: International Meeting on Artificial Intelligence and its Applications (RIIAA) 2.0.
    workshop: Workshop – Deep Learning as a Service (DLaaS), August 2019.
    material: https://github.com/RodolfoFerro/RIIAA19-DLaaS
    link: https://riiaa.org
  item3:
    event: LAB León Web Dev Crash Course 2019.
    workshop: Crash Course – Introduction to Web Development with Python and Flask, August 2019.
    material: https://github.com/RodolfoFerro/Flask101
    link: https://flask101.glitch.me
  item4:
    event: DevDay León 2019 by Hackademy.
    workshop: Workshop – (AI) API development with Python, August 2019.
    material: https://github.com/RodolfoFerro/PythonBaseAPI
    link:
  item5:
    event: Clubes de Ciencia México 2019.
    workshop: Workshop – Revealing the Hidden Hyperspectrum with Artificial Neurons, July 2019.
    material: https://rodolfoferro.xyz/hyperspectrum/
    link:
  item6:
    event: DevDay Mérida 2019.
    workshop: Workshop – Artificial Intelligence with Python, July 2019.
    material: https://github.com/RodolfoFerro/DevDayMid2019
    link:
  item7:
    event: Talent Land 2019.
    workshop: Talk – A.I. in modern times, April 2019.
    material:
    link: https://jaliscotalentland2019.sched.com/event/MzAs/inteligencia-artificial-en-tiempos-modernos
  item8:
    event: PythonDay México 2018.
    workshop: Talk – Data Science with Python, December 2018.
    material: https://github.com/RodolfoFerro/DataSciPy
    link:
  item9:
    event: PythonDay México 2018.
    workshop: Workshop – Machine Learning as a Service (MLaaS), November 2018.
    material: https://github.com/RodolfoFerro/MLaaS
    link:
  item10:
    event: HERE Hackathon at Technological University of Leon.
    workshop: Mentor on the event. Talk – Integration of Technological Solutions, November 2018.
    material: https://github.com/RodolfoFerro/HereHackathon
    link:
  item11:
    event: 6th. International Conference in Software Engineering Research and Innovation (CONISOFT).
    workshop: Workshop – Introduction to Neural Networks with Keras, October 2018.
    material: https://github.com/RodolfoFerro/CONISOFT2018
    link: http://conisoft.org/2018/public/
  reference: https://rodolfoferro.xyz/resume/


# Projects section
projects:
  item1:
    title: flask-resume-template
    subtitle: A resume template built with Flask
    description: An easy-to-configure simple resume template built with Flask and Bootstrap.
    link: https://flask-resume-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-resume-template/
    img: flask-resume-template.png
    tags: [Flask, Python, Bootstrap]
  item2:
    title: DLaaS
    subtitle: Google Colab Notebooks
    description: A set of Google Colab notebooks and a Flask base API to learn and serve Deep Learning. Prepared for my workshop at RIIAA 2.0.
    link: https://rodolfoferro.xyz/RIIAA19-DLaaS/
    github: https://github.com/RodolfoFerro/RIIAA19-DLaaS
    img: riiaa.png
    tags: [Python, Tensorflow 2.0, Keras, Deep Learning]
  item3:
    title: impipes
    subtitle: Python package
    description: A Python package to build image pipelines in a simple way. Preprocess data to feed neural networks in an easier way.
    link: https://impipes.readthedocs.io/en/latest/
    github: https://github.com/RodolfoFerro/impipes
    img: impipes.png
    tags: [Python, PyPI, Images, Data Preprocessing, Documentation]
  item4:
    title: MNIST Web Classifier
    subtitle: A CNN served as a web platform
    description: Classify handwritten digits directly on your computer or your phone. As simple as taking a picture of a written random multi-digit number.
    link: https://flask-micro-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-micro-template
    img: keras-mnist.png
    tags: [Python, Bootstrap, Web Platform, Flask, MNIST, CNN, Keras]
  item5:
    title: EmojiMerida
    subtitle: Google Colab Notebook
    description: A real-time coding session with an emotion recognizer on facial expressions for a Data Mérida meetup (01/04/2019). The Ai was developed with Python and Keras.
    link: https://colab.research.google.com/github/RodolfoFerro/EmojiMerida/blob/master/Data_M%C3%A9rida.ipynb
    github:
    img: data-merida.png
    tags: [Python, Computer Vision, Keras, Neural Networks]
  item6:
    title: PythonBaseAPI
    subtitle: API template built with Flask
    description: API template built with Python and Flask. Serve an Iris classifier as an API. Content for a workshop.
    link: https://docs.google.com/presentation/d/e/2PACX-1vSc7Q82-lwQ8fKgR5WcT7Y0r9kotcYiNuyYjHRlF-fdhf6lkIrF9B_2akvzL-ZQ6ZAyT1lxM9f0mPdx/pub?start=false&loop=false&delayms=3000
    github: https://github.com/RodolfoFerro/PythonBaseAPI
    img: python-base-api.png
    tags: [Flask, Python, API, scikit-learn]
  item7:
    title: flask-micro-template
    subtitle: A micro template built with Flask
    description: A micro template built with Flask and Bootstrap. Used for minimal testing in Glitch.
    link: https://flask-micro-template.glitch.me
    github: https://github.com/RodolfoFerro/flask-micro-template
    img: flask-micro-template.png
    tags: [Flask, Python, Bootstrap]
  item8:
    title: moltransform
    subtitle: Python package
    description: Molecular transformations for graphic displaying using Cartesian coordinates.
    link: https://pypi.org/project/moltransform/
    github: https://github.com/RodolfoFerro/moltransform
    img: moltransform.png
    tags: [Python, PyPI, Molecules, Rigid Transformations]
  item9:
    title: FitbitVersa-SimpleOmnitrix
    subtitle: Fitbit Versa Clockface
    description: My first clock face for Fitbit Versa, inspired in Ben 10's Omnitrix.
    link: https://gallery.fitbit.com/details/6c75fa41-8de0-41db-b851-f21f7447018b
    github: https://github.com/RodolfoFerro/FitbitVersa-SimpleOmnitrix
    img: simple-omnitrix.png
    tags: [TypeScript, Ben 10, Fitbit, Fitbit Versa]


# Certifications and awards section
certifications:
  - SAFe Agilist - 2021
  - Scrum Product Owner (SBB AG internal Training) - 2020
  - Scrum Master (The Scrum Alliance) - 2019/2020

